### PR TITLE
ru-RU translation of Core, CmdLine, ConsoleUI, and AutoUpdate

### PR DESCRIPTION
**Pull request by nt0g**
May contain errors, will complete (translate CmdLine and correct errors) later. I need to see how it looks first.

___

To be added to KSP-CKAN#3482

### CODE REVIEW

**Comment by nt0g** [comment]
Ah, this went terribly wrong somewhere. This is what I get for trying to work while being sleep deprived with an allergy attack.

**Comment by HebaruSan** [comment]
Nah, I think it's because I force-pushed my branch to fix up some things with the earlier commits. Rebasing this should help, I'll give that a try...

**Comment by HebaruSan** [comment]
Should be OK now, the conflicts are gone and it's only showing 2 changed files and one commit. :tada:

**Comment by HebaruSan** [comment]
The test build should be here so you can see how it looks:

- https://github.com/HebaruSan/CKAN/suites/4433061344/artifacts/117389619

**Comment by HebaruSan** [comment]
```
$ LC_ALL=ru_RU.utf-8 ckan.exe consoleui
```

image

:joy:

**Comment by nt0g** [comment]
Please explain, can I use Cyrillic characters for CmdLine like this or will it only respond to **y/n**?

Screenshot 2021-11-23 090849

**Comment by HebaruSan** [comment]
For CmdLine, `UserYesNoPromptSuffix` and `UserYesNoInvalid` are displayed to the user, and  `UserYesNoY`, `UserYesNoYes`, `UserYesNoN`, and `UserYesNoNo` are used to interpret the user's input. It will respond to the values that you choose for those strings.

**Review by HebaruSan — APPROVED** [review]
This looks good to me, thanks for the contribution! I'm happy to merge it as soon as you are ready. Are you planning to make more changes?

**Comment by nt0g** [comment]
One more commit and it should be ready, but I have a question.
"ModListPressAKey" string means "Press any key" or "Press «A» key"?

**Comment by HebaruSan** [comment]
That message is displayed when you run `ckan consoleui --debug` to enable the "Capture key" menu option, which we use when someone has a problem with one of the keybindings, since different operating systems may have quirks with how they handle keys:

image

&rArr;

image

&rArr;

image

I guess the intent of the string is closer to "press a key" rather than "press any key", since "press any key" is usually used to dismiss a dialog, whereas here we are capturing the key and presenting information about it.

**Comment by nt0g** [comment]
Okay, I think this is good enough.

**Pull request merged**
